apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka1
  namespace: deep-kafka
spec:
  replicas: 1
  selector:
    app: kafka1
  template:
    metadata:
      labels:
        app: kafka1
    spec:
      containers:
      - name: kafka1
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: $(MY_POD_IP)
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka2
  namespace: deep-kafka
spec:
  replicas: 1
  selector:
    app: kafka2
  template:
    metadata:
      labels:
        app: kafka2
    spec:
      containers:
      - name: kafka2
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KAFKA_BROKER_ID
          value: "2"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: $(MY_POD_IP)
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka3
  namespace: deep-kafka
spec:
  replicas: 1
  selector:
    app: kafka3
  template:
    metadata:
      labels:
        app: kafka3
    spec:
      containers:
      - name: kafka3
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KAFKA_BROKER_ID
          value: "3"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: $(MY_POD_IP)
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181
