apiVersion: v1
kind: Pod
metadata:
 name: kafkacat-producer-pod1
 namespace: deep-kafka
spec:
 containers:
 - name: kafkacat
   image: confluentinc/cp-kafkacat
   ports: [{containerPort: 80}]
   command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
