apiVersion: v1
kind: Pod
metadata:
 name: python-consumer
spec:
 containers:
 - name: python-consumer
   image: deepbmehta/python3
   ports: [{containerPort: 80}]
   command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
